// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6Br-A4zCDi0dHsxdANfVRqElte_VOa4',
    appId: '1:724990847891:web:7567b46bd6740332559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    authDomain: 'ourverses-dev.firebaseapp.com',
    storageBucket: 'ourverses-dev.appspot.com',
    measurementId: 'G-LR2CY6K7VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsgS1YhU7WE1oeBg9LqVDABwCsvt9BcM4',
    appId: '1:724990847891:android:f2ea2a0a05fad3bb559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJHCGMj1Gm2SGGCYgKjz4OX9q_gmeTcs',
    appId: '1:724990847891:ios:452cf4d55d251ed0559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
    iosClientId: '724990847891-i9sa4fggdc8pjjbiq26p9f0n3c5r4tkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJHCGMj1Gm2SGGCYgKjz4OX9q_gmeTcs',
    appId: '1:724990847891:ios:452cf4d55d251ed0559666',
    messagingSenderId: '724990847891',
    projectId: 'ourverses-dev',
    storageBucket: 'ourverses-dev.appspot.com',
    iosClientId: '724990847891-i9sa4fggdc8pjjbiq26p9f0n3c5r4tkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstProject',
  );
}
